#!/bin/csh
set runnum = $1
set output = "/home/lthorne/compton/CompMon/rootfiles/compmon_"$runnum".root"
rm lnkCompMon.output
ln -s $output lnkCompMon.output
rm $output
rm lnkCompMon.input
set input = "/home/lthorne/compton/ComptonData/test_"$runnum".dat"
ln -s $input lnkCompMon.input
compmon $runnum  1000000


